# Generated by Django 6.0.4 on 2026-05-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bg_img',
            field=models.ImageField(null=True, upload_to='ipl/images'),
        ),
    ]
