# Generated by Django 6.0.4 on 2026-05-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0002_team_bg_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(choices=[('Batter', 'Batter'), ('Bowler', 'Bowler'), ('All Rounder', 'All Rounder'), ('Wicket Keeper', 'Wicket Keeper')], max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='ipl/images')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ipl.team')),
            ],
        ),
    ]
