# Generated by Django 6.0.4 on 2026-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Batter', 'Batter'), ('Bowler', 'Bowler'), ('All Rounder', 'All Rounder'), ('Wicket Keeper, Batter', 'Wicket Keeper, Batter')], max_length=100),
        ),
    ]
