# Generated by Django 6.0.4 on 2026-05-12 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0004_alter_player_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Completed', 'Completed')], default='Upcoming', max_length=20)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='ipl.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='ipl.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='ipl.team')),
            ],
        ),
    ]
