# Generated by Django 6.0.4 on 2026-05-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0005_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
