# Generated by Django 6.0.4 on 2026-05-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0006_player_is_playing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('overs', models.FloatField()),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_scores', to='ipl.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_scores', to='ipl.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='ipl.match')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('dismissal_type', models.CharField(blank=True, max_length=100, null=True)),
                ('overs', models.FloatField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('maidens', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('run_outs', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scorecards', to='ipl.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='ipl.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_scorecards', to='ipl.team')),
            ],
        ),
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('no_results', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('runs_scored', models.IntegerField(default=0)),
                ('overs_faced', models.FloatField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('overs_bowled', models.FloatField(default=0)),
                ('net_run_rate', models.FloatField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_table', to='ipl.team')),
            ],
        ),
    ]
