# Generated by Django 6.0.4 on 2026-05-12 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0007_matchscore_playerscorecard_pointstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingXI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_wicket_keeper', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing_xi', to='ipl.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.team')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_up_finishes', to='ipl.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_wins', to='ipl.team')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(choices=[('Orange Cap', 'Orange Cap'), ('Purple Cap', 'Purple Cap'), ('MVP', 'MVP'), ('Emerging Player', 'Emerging Player')], max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.tournament')),
            ],
        ),
    ]
