# Generated by Django 6.0.4 on 2026-05-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0008_playingxi_tournament_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('League', 'League'), ('Qualifier 1', 'Qualifier 1'), ('Eliminator', 'Eliminator'), ('Qualifier 2', 'Qualifier 2'), ('Final', 'Final')], default='League', max_length=30),
        ),
    ]
